### ISSUE TITLE
Data Dashboard QA & Feedback

### ISSUE THREAD

**Issue by owocki** [gitcoinco/data-ops#4] opened 2018-07-30 19:21 UTC
# Lifetime OKRs dashboard ( and Q3 OKRs )

- [x] 1. can we update bounty status distribution to include expired and cancelled bounties?
- [x] 2. "Bounties: Lifetime Bounty Distribution by Status, MoM (All Active Bounties)" is a cohort analysis of when the bounty was created, and its status now right?  so its designed to help us find the straggler bounties?
- [x] 3. for "Bounties: Lifetime Bounty Distribution by Status, MoM (All Active Bounties)" -- can we add expired/cancelled bounties?
- [x] 4. can we add 'lifetime email subscribers' to the dashboard?
- [x] 5. it might be more accurate to rename 'Users: Lifetime Bounty Hunters' to 'lifetime users' since we dont know if they are bounty hunters or not
- [x] 6. can we add 'active users' where last_login > 30 days ago? 
- [x] reorganize Lifetime / OKR dashboard

# Marketing Dashboard 
- [x] 1. the top two charts seem kind of duplicates of one another.  i think we can drop the % change one
- [x] 2. retention rate is 0 the last few days.. why?
- [x] 3. whats the diff between new/returning user retention rate?
- [x] 4. whats 'engagement rate'?
- [x] 4. meta question: is there a way to add a description to a question on a dashboard so user can see this context when they hover on it?)
- [x] 5. meta question about all "%" change dashboards.  is it worth just showing the raw number of change day over day insteaad of "%" change?
- [x] 6. can we change the 'num twitter followers' graph to be consistent with the other graphs and show day over day change instead of rote numbers?
- [x] reorganize Marketing dashboard

# Opex Dash

- [x] 1.  first graph stops on the 23rd, 2nd graph on the 30th.  seemes inconsistent to me
- [x] 2. can we change the top right graph to be labeled 'by work' to 'by USD exchanged'?  i thikn thats the right metric right? 
- [x] 3. for the first two graphs, can we also show the num expired/cancelled bounties?
- [x] 4. similar to marketing dashboard, i'd recommend changing the "%" changed metrics to just show the raw volume
- [x] 5. 'average bounty throughput'  this is cool!
- [x] 6. bounty rates => can we express these as a percentage?
- [x] 7. for each of the bounty rates, itd be cool to see a link to the bounty below the number, so i can clickthrough and examine why a bounty is 'stale/abanadoned/whatever'.
- [x] 8. i'd be curious to hear from @vs77bb if this 'abanadoned' bounty tool ( http://bits.owocki.com/3s0U1w2Y1H0p/Screen%20Shot%202018-07-30%20at%201.18.15%20PM.png ) will be useful to him
- [x] https://andrewchen.co/power-user-curve/ # of folks who were active on the platform >15, 20, 25 days?
- [x] reorganize OpEx dash

# Scott's request 2018-08-24
- [x] count of new projects and issues by new repos, last 7 days
- [x] detailed view of new repos, projects, and issues
- [x] count of new repos, projects, and issues, last 7 days (metabot)
- [x] new projects, DoD
- [x] total projects, DoD
- [x] total lifetime projects
- [x] Q3 projects 
- [x] count of projects and issues by new repos using Gitcoin (rollup of all time)

**Comment by frankchen07** [comment] 2018-08-08 15:46
### Lifetime OKR Dashboard responses

2. Bounties: Lifetime Bounty Distribution by Status, MoM (All Active Bounties) was designed more towards looking at the distribution of each status. So if we see that 19% of active bounties were open in June, and 12% were open in July, and 10% in August, that might prompt us to ask, are the bounties moving towards done, or are less bounties being opened month over month? 

I also realize that because we're using created date, the distribution might not be accurate for projects that span beyond the month (if the projects are long, then projects created in a certain month will most certainly be open or started, not necessarily done). This is to say, if Gitcoin has longer, larger projects, the distribution will skew towards bounties not being done within the month. 

### Marketing Dashboard responses

2. A user is considered "retained" when they perform an action on day X and return anytime on or after day X+7. Rolling retention is used as a measure of stickiness and lets us know how many customers we've successfully built relationships with. For example, a retention rate of 77% on April 28th means of the users who perform an action on April 28th, 77% return a week later and beyond. Retention for the most recent week will be 0 because we would be looking at the future, which hasn't happened.

3. A user is considered "retained" when the user performs any action on the Gitcoin platform on day X and day X+1. For example, a retention rate of 30% on April 23rd means 30% of users who performed an action on April 22nd performed an action on April 23rd. New user retention is calculated where only actions on a user's join date are considered. The opposite holds true for existing users. 

4. Engagement on Gitcoin is defined as the percentage of users who logged in and started work out of the users who simply logged in, by day. Engagement on Slack is defined as the percentage of users who are online out of the users who are Gitcoin Slack users, by day.

4. There is a way to add descriptions. The appropriate context has been added for retention and engagement metrics and more complex items. (more to be added as we find vague or unclear items).

### Opex Dashboard responses

7.  @owocki - can you clarify number 7 for me and how it's different from number 8?

8. @vs77bb - this is essentially similar to the advanced filtering options on the issue explorer - but depending on what you specifically like to look at, we can build in additional logic on the dashboard.

**Comment by owocki** [comment] 2018-08-08 22:43
@frankchen07 i think that 7 and 8 are the same.  just checked it off now

**Closed** 2018-09-06 22:32 UTC
